### ISSUE TITLE
Flex Sensor Followup

### ISSUE THREAD

**Issue by marc25v** [arsenicks/pyhydroquebec-hass-addons#11]
Hey Arsenicks!

Thanks for letting us know.  Do you think you could use the following repo instead: https://github.com/tech165/pyhydroquebec

Seems to be live with the Flex Sensor.

Thanks again # #10 #

**Comment by arsenicks** [comment]
Hi, as stated before I can't. I build the container image by installing pyhydroquebec with pip. So I can't simply point to another repo because I don't use any repo, only packages available in public pypi repository, for doing what you want it would require a new Dockerfile to clone your repo probably build few thing and use the script as entrypoint. You are free to fork this repo and complete the modification if you want, everything is available here for you to do it but I won't..

Mainly because I don't use this addon anymore, I'm using Hilo now so I get all the data I want from the Hilo devices and the usage from my meter directly..

Thanks, have a great day!
