### ISSUE TITLE
@ caracter in password

### ISSUE THREAD

**Issue by MarcAnt1** [arsenicks/pyhydroquebec-hass-addons#14]
Just to let people now that the script doesn't like having a "@" in the password, I've just changed my password.

**Comment by arsenicks** [comment]
I'll take a look at that soon. pyhydroquebec is in the process of being re-written from scratch. I will release few minor test version soon and once it's stable I'll release a new stable release.

**Comment by arsenicks** [comment]
Hi, I've neglected this repository. This project is now unsupported because the pyhydroquebec python library I used has been renamed and reworked from scratch.

Don't feel bad, it's now really better and there's a addon you can use in HA too. I will update the readme here to reflect those information.

New project website: https://hydroqc.ca/fr/
Gitlab project: https://gitlab.com/hydroqc
Hass-addon repository: https://gitlab.com/hydroqc/hydroqc-hass-addons

There's a Discord if you have questions or want to contribute: https://discord.gg/2NrWKC7sfF

I'll close this issue and the other than update the readme with the information above.

Thanks, have a great day!
