### ISSUE TITLE
Still Unknow data

### ISSUE THREAD

**Issue by drdoom1976** [arsenicks/pyhydroquebec-hass-addons#15]
Hi

Installed and configured the plugin.  Seems working fine but all the 14 entities reports unknow data for the first 4 hours.
How long should it takes to receive data from Hydro-Québec ?

Thanks.

**Comment by drdoom1976** [comment]
Found these in HA logs

Failed to to call /addons/d3d9ed6e_pyhydroquebec/stats - Can't read stats from addon_d3d9ed6e_pyhydroquebec: Expecting value: line 1 column 1 (char 0)
Failed to to call /addons/d3d9ed6e_pyhydroquebec/stats - Container addon_d3d9ed6e_pyhydroquebec is not running

Thanks.

**Comment by arsenicks** [comment]
Hi, I've neglected this repository. This project is now unsupported because the pyhydroquebec python library I used has been renamed and reworked from scratch.

Don't feel bad, it's now really better and there's a addon you can use in HA too. I will update the readme here to reflect those information.

New project website: https://hydroqc.ca/fr/
Gitlab project: https://gitlab.com/hydroqc
Hass-addon repository: https://gitlab.com/hydroqc/hydroqc-hass-addons

There's a Discord if you have questions or want to contribute: https://discord.gg/2NrWKC7sfF

I'll close this issue and the other than update the readme with the information above.

Thanks, have a great day!
