### ISSUE TITLE
Config file is not generating automaticaly

### ISSUE THREAD

**Issue by nips1900** [arsenicks/pyhydroquebec-hass-addons#5]
Hi,

just a heads up, it seems that this file /config/pyhq-config.yaml is not generating automatically by the Configuration tab of the addon.

I had to create and fill it out manual according to your template.

Otherwise everything works great!

thank you for creating this add-on.

Laurent

**Comment by arsenicks** [comment]
Hi, yes I'm aware of that and as it is right now we have to duplicate the info in the config file AND inside the add-on. I wasn't successful in my first tests so I shipped it like that but I have to put some work in there to better understand how pyhydroquebec work.

I don't modify the code of the original project, so I must provide the variables it want at launch. If I recall I wasn unable to provide only environment variables, I had to put the yaml config file.

I'll keep this open because I might need to add precision regarding this in the README and this was on my todo list.

Thanks for reporting.

**Comment by mvonh** [comment]
Any way to get the stats from this to play nice with the new energy tracking features?  Seems like we get daily totals from the prior day and a running total.  I guess using the Utility Meter integration is the way to go?

**Comment by arsenicks** [comment]
> Any way to get the stats from this to play nice with the new energy tracking features? Seems like we get daily totals from the prior day and a running total. I guess using the Utility Meter integration is the way to go?

I didn't try this but another user posted this: https://github.com/arsenicks/pyhydroquebec-hass-addons/issues/9#issuecomment-990333908

This might help you.

**Comment by arsenicks** [comment]
Hi, I've neglected this repository. This project is now unsupported because the pyhydroquebec python library I used has been renamed and reworked from scratch.

Don't feel bad, it's now really better and there's a addon you can use in HA too. I will update the readme here to reflect those information.

New project website: https://hydroqc.ca/fr/
Gitlab project: https://gitlab.com/hydroqc
Hass-addon repository: https://gitlab.com/hydroqc/hydroqc-hass-addons

There's a Discord if you have questions or want to contribute: https://discord.gg/2NrWKC7sfF

I'll close this issue and the other than update the readme with the information above.

Thanks, have a great day!
