### ISSUE TITLE
Accessing data and configuration

### ISSUE THREAD

**Issue by geniusled** [arsenicks/pyhydroquebec-hass-addons#8]
Hello, ive installed the addon successully, the hydroqc account configuration seems to work but i cannot get data from it.

in the log, it will login and get to fetching yesterday data,then wait 10800 seconds before next check.

i created a mqtt sensor on the same topic as the one in the configuration page but it does not seem to receive anything,
is there more documentation available on how to get/use the data ?

Thank you
-Phil

**Comment by arsenicks** [comment]
Hi, just to clear things out I can try to help but any issue with pyhydroquebec should be raised on their [github issue page](https://github.com/titilambert/pyhydroquebec/issues). That being said, it looks like you get your data but it doesn't show in hass ? Please explain to me where did you look for data.

Unfortunately clear documentation has been lacking, the add-on is a side project **using** pyhydroquebec, I have no control over bugs, features or anything regarding pydroquebec. I only control the hass add-on side, so here's my two cents.

look in your home assistant -> Configuration -> Entities and filter with hydroquebec you should already see around 15 entities automatically created by the MQTT integration. Ex. hydroquebec_CONTRACTNUMBER_period_total_bill etc.. You should be able to see data in there, if you don't you'll have to find out why..

Try enabling debug and watch for errors, warning etc..

You can install mosquitto_sub on your computer and try to listen to mqtt event.

$ mosquitto_sub -h homeassistant.localdomain -v -u mosquittousername -P mosquittopassword -t h3 -t homeassistant/#

restart the pyhydroquebec addon and after ~15seconds you should see data published on the topic homeassistant/sensor/hydroquebec_123456 where 123456 is your contract number. if you see this, everything is good, otherwise it probably means the addon can't contact your mqtt server, doublecheck your username/password hosts configuration in the addon yaml and in the config page.

**Comment by geniusled** [comment]
thanks for the answer, i have figured out my issues.
- mqtt password was not the one i set in the end in mosquitto, wierd but now works
- state_topic must be "homeassistant" in order for mqtt discovery to add the entities
- the debug log indicates mqtt connection issues only after the interval indicated in pyhq-config.yaml

**Comment by arsenicks** [comment]
I will try to update the documentation soon to cover those details(state topic and other options)! I think there's a way to use the mqqt integration installed and user/pass without user having to figure it out, it will be easier for people not familiar with it. I'll have to put some work in there.

I'll close the issue as your problem is fixed!
