### ISSUE TITLE
Hourly data

### ISSUE THREAD

**Issue by krandof** [arsenicks/pyhydroquebec-hass-addons#9]
Hello, 
First i would like to thank you, the add-on work well (got some issue to make it work but normal as im not a MQTT guru :) 

Looking at the data that is fetch, we have the information of yesterday... Would it be possible to add in the configuration additional time range that we could fetch?

Thanks,

**Comment by sibromtl** [comment]
Hello, 
I second @krandof comments... Just installed this add-on two days ago. Works great to get past day data although I got weird results (negative consumption at 3 am yesterday!) when trying to integrate these data in the new Energy tab of Home Assistant (still working on it). It would also be great to have the hourly data that we could get via CLI. 
Thanks for what has been already accomplished.

**Comment by MatheGeek** [comment]
@sibromtl 
I created 2 sensors that comply with the requirements of the HA Energy Dashboard.
I've detailed how I did it there : https://github.com/MatheGeek/pyhydroquebec-integration-to-HA-Energy-Dashboard
Never got negative result and  it's still look OK  after completing a billing cycle.   Hope it helps.

**Comment by krandof** [comment]
@MatheGeek  Your solution work well to be compatible Thanks. At the moment that we can get Hourly consumption and everythin within the add-on we will be in super shape to integrate HydroQuebec within HA. HydroQuebec should open their API the same way they done for Hilo... our life would be so much easier :)... But thanks all

**Comment by arsenicks** [comment]
Hi, I'll have to update the README to clearly state I cannot change any features other than the "add-on" part.. I really just use the pypi package and build a container with files HASSOS use to show as an addon. So any bug/feature/changes can't be fixed by me, those must be submitted to https://github.com/titilambert/pyhydroquebec/issues

@krandof FYI Hilo hasn't opened their API, AFAIK. The custom integration in HA has been made by getting the android apk package, open it and "reverse engineer" the API calls.. So this could stop working without warning, I think they don't want to open too much, they want to keep control over their stuff. As for HD, I've wrote to them few times on different entry point, the team of "donnée ouverte" told me there's no API to consume right now but they are "working on something" whatever that mean..

I'll close this issue as I can't do anything, but I'll try to make a new release soon with better doc and I hope will be able to fix the yaml requirement to just use the add-on config page. If I recall correctly, the yaml config file is required by pyhydroquebec but there's probably a way to hack this.

BTW any contribution is welcome guy's in case someone want to step in! I will receive my Hilo setup next week so I will stop using this add-on... I plan to still support it as there's not much work to do in case a new release of pyhydroquebec magically appear but I will certainly loose interest to put more time in fixing the config thing if it require a lot of work.. :(

**Comment by sibromtl** [comment]
@MatheGeek Thanks for your feedback. I’ve realized that I was using the “yesterday” sensor instead of the “total” sensor ! After customizing this sensor in HA (device_class, units, etc) to make sure it complies with HA requirements, I got exact daily consumption values in HA Energy tab, at 3 am for the past 2 days… The only problem I am facing now is that this daily consumption in the Energy tab is offset by one day (for example consumption from yesterday Dec. 10 appears on today Dec 11 page at 3 am). Does anybody have the same issue?

@arsenick, I would love to be able to contribute, but unfortunately, my programming skills are very limited. Thanks for your great work for this add-on !

**Comment by MatheGeek** [comment]
> Does anybody have the same issue?

@sibromtl  Yeah as the update at 3 AM push the data of the day before,  I have the same issue.  I didn't had time to work on it yet.   I'll let you know if I find a way to correct it.
